---
- name: create a new key pair
  amazon.aws.ec2_key:
    name: "{{ aws_key_name }}"
    region: "{{ aws_region }}"
  register: key_pair

- name: get private key
  set_fact:
    private_key: "{{ key_pair.key.private_key }}"
  when: key_pair['msg'] != 'key pair already exists'

- name: create private key on localhost
  ansible.builtin.template:
    src: templates/private_key
    dest: "~/.ssh/{{ aws_key_name }}.pem"
    mode: '0400'
  when: key_pair['msg'] != 'key pair already exists'

- name: create security group
  amazon.aws.ec2_security_group:
    name: "{{ aws_security_group }}"
    description: an example EC2 group
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        ports:
          - 443
          - 80
          - 22
        cidr_ip: 0.0.0.0/0

- name: provision ec2 instance
  amazon.aws.ec2_instance:
    instance_type: "{{ aws_instance_type }}"
    image_id: "{{ aws_image_id }}"
    exact_count: 1
    region: "{{ aws_region }}"
    security_group: "{{ aws_security_group }}"
    network:
      assign_public_ip: true
    key_name: "{{ aws_key_name }}"
    state: running
    tags: 
      environment: "{{ aws_tag }}"